//! Std methods/macros that are not keywords. Verbs like usa: clona, empuja, mapea.
//! Short tech that already works in Spanish stays: ok, err, max, min, vec, zip, dbg.

#[derive(Clone, Copy)]
pub struct Par {
    pub en: &'static str,
    pub es: &'static str,
}

pub const PRELUDE: &[Par] = &[
    // convert
    Par { en: "new", es: "nuevo" },
    Par { en: "into", es: "hacia" },
    Par { en: "from", es: "desde" },
    Par { en: "try_into", es: "intenta_hacia" },
    Par { en: "try_from", es: "intenta_desde" },
    Par { en: "From", es: "Desde" },
    Par { en: "Into", es: "Hacia" },
    Par { en: "TryFrom", es: "IntentaDesde" },
    Par { en: "TryInto", es: "IntentaHacia" },
    Par { en: "into_iter", es: "hacia_iter" },
    Par { en: "into_bytes", es: "hacia_bytes" },
    Par { en: "into_string", es: "hacia_texto" },
    Par { en: "into_boxed_slice", es: "hacia_caja_slice" },
    Par { en: "from_iter", es: "desde_iter" },
    Par { en: "from_fn", es: "desde_fn" },
    Par { en: "from_utf8", es: "desde_utf8" },
    Par { en: "from_utf8_lossy", es: "desde_utf8_lossy" },
    Par { en: "as_ref", es: "como_ref" },
    Par { en: "as_mut", es: "como_mut" },
    Par { en: "as_str", es: "como_str" },
    Par { en: "as_bytes", es: "como_bytes" },
    Par { en: "as_slice", es: "como_slice" },
    Par { en: "as_mut_slice", es: "como_mut_slice" },
    Par { en: "to_string", es: "a_texto" },
    Par { en: "to_owned", es: "a_propio" },
    Par { en: "to_vec", es: "a_vec" },
    Par { en: "to_lowercase", es: "a_minusculas" },
    Par { en: "to_uppercase", es: "a_mayusculas" },
    Par { en: "parse", es: "parsea" },
    // clone / default / drop
    Par { en: "clone", es: "clona" },
    Par { en: "cloned", es: "clonado" },
    Par { en: "copied", es: "copiado" },
    Par { en: "clone_from", es: "clona_desde" },
    Par { en: "default", es: "defecto" },
    Par { en: "Default", es: "Defecto" },
    Par { en: "drop", es: "suelta" },
    Par { en: "swap", es: "intercambia" },
    Par { en: "forget", es: "olvida" },
    // option / result
    Par { en: "unwrap", es: "desenvuelve" },
    Par { en: "unwrap_or", es: "desenvuelve_o" },
    Par { en: "unwrap_or_else", es: "desenvuelve_o_sino" },
    Par { en: "unwrap_or_default", es: "desenvuelve_o_defecto" },
    Par { en: "expect", es: "exige" },
    Par { en: "map", es: "mapea" },
    Par { en: "map_err", es: "mapea_err" },
    Par { en: "map_or", es: "mapea_o" },
    Par { en: "map_or_else", es: "mapea_o_sino" },
    Par { en: "and_then", es: "y_entonces" },
    Par { en: "or_else", es: "o_sino" },
    Par { en: "flatten", es: "aplana" },
    Par { en: "ok_or", es: "ok_o" },
    Par { en: "ok_or_else", es: "ok_o_sino" },
    Par { en: "is_some", es: "es_alguno" },
    Par { en: "is_none", es: "es_ninguno" },
    Par { en: "is_ok", es: "es_ok" },
    Par { en: "is_err", es: "es_err" },
    Par { en: "Some", es: "Alguno" },
    Par { en: "None", es: "Ninguno" },
    Par { en: "take", es: "toma" },
    Par { en: "replace", es: "reemplaza" },
    // vec / slice / string
    Par { en: "len", es: "largo" },
    Par { en: "is_empty", es: "esta_vacio" },
    Par { en: "push", es: "empuja" },
    Par { en: "push_str", es: "empuja_str" },
    Par { en: "pop", es: "saca" },
    Par { en: "insert", es: "inserta" },
    Par { en: "remove", es: "quita" },
    Par { en: "clear", es: "limpia" },
    Par { en: "retain", es: "retiene" },
    Par { en: "extend", es: "extiende" },
    Par { en: "append", es: "anexa" },
    Par { en: "truncate", es: "trunca" },
    Par { en: "resize", es: "redimensiona" },
    Par { en: "reserve", es: "reserva" },
    Par { en: "capacity", es: "capacidad" },
    Par { en: "get", es: "obten" },
    Par { en: "get_mut", es: "obten_mut" },
    Par { en: "contains", es: "contiene" },
    Par { en: "sort", es: "ordena" },
    Par { en: "reverse", es: "invierte" },
    Par { en: "first", es: "primero" },
    Par { en: "last", es: "ultimo" },
    Par { en: "split", es: "parte" },
    Par { en: "split_at", es: "parte_en" },
    Par { en: "split_off", es: "separa" },
    Par { en: "split_whitespace", es: "parte_espacios" },
    Par { en: "drain", es: "drena" },
    Par { en: "fill", es: "llena" },
    Par { en: "repeat", es: "repite" },
    Par { en: "starts_with", es: "empieza_con" },
    Par { en: "ends_with", es: "termina_con" },
    Par { en: "strip_prefix", es: "quita_prefijo" },
    Par { en: "strip_suffix", es: "quita_sufijo" },
    Par { en: "trim", es: "recorta" },
    Par { en: "trim_start", es: "recorta_inicio" },
    Par { en: "trim_end", es: "recorta_fin" },
    Par { en: "lines", es: "lineas" },
    Par { en: "with_capacity", es: "con_capacidad" },
    // iterator
    Par { en: "collect", es: "recolecta" },
    Par { en: "filter", es: "filtra" },
    Par { en: "filter_map", es: "filtra_mapea" },
    Par { en: "find", es: "encuentra" },
    Par { en: "find_map", es: "encuentra_mapea" },
    Par { en: "fold", es: "pliega" },
    Par { en: "reduce", es: "reduce" },
    Par { en: "sum", es: "suma" },
    Par { en: "count", es: "cuenta" },
    Par { en: "skip", es: "salta" },
    Par { en: "take_while", es: "toma_mientras" },
    Par { en: "skip_while", es: "salta_mientras" },
    Par { en: "chain", es: "encadena" },
    Par { en: "enumerate", es: "enumera" },
    Par { en: "inspect", es: "inspecciona" },
    Par { en: "cycle", es: "cicla" },
    Par { en: "for_each", es: "para_cada" },
    Par { en: "any", es: "alguno" },
    Par { en: "all", es: "todos" },
    Par { en: "position", es: "posicion" },
    Par { en: "next", es: "siguiente" },
    Par { en: "nth", es: "enesimo" },
    Par { en: "by_ref", es: "por_ref" },
    Par { en: "size_hint", es: "pista_tamano" },
    Par { en: "flat_map", es: "mapea_plano" },
    Par { en: "step_by", es: "paso" },
    Par { en: "partition", es: "particion" },
    // macros (bang kept, except print* handled in translate)
    Par { en: "format", es: "formato" },
    Par { en: "panic", es: "panico" },
    Par { en: "assert", es: "afirma" },
    Par { en: "assert_eq", es: "afirma_eq" },
    Par { en: "assert_ne", es: "afirma_ne" },
    Par { en: "unimplemented", es: "no_implementado" },
    Par { en: "unreachable", es: "inalcanzable" },
    Par { en: "write", es: "escribe" },
    Par { en: "writeln", es: "escribe_ln" },
    // types (rustc never sees these; we roundtrip)
    Par { en: "Vec", es: "Lista" },
    Par { en: "String", es: "Texto" },
    Par { en: "str", es: "texto" },
    Par { en: "Option", es: "Opcion" },
    Par { en: "Result", es: "Resultado" },
    Par { en: "HashMap", es: "MapaHash" },
    Par { en: "HashSet", es: "ConjuntoHash" },
    Par { en: "BTreeMap", es: "MapaOrd" },
    Par { en: "BTreeSet", es: "ConjuntoOrd" },
    Par { en: "VecDeque", es: "Cola" },
    Par { en: "LinkedList", es: "ListaEnlazada" },
    Par { en: "Iterator", es: "Iterador" },
    Par { en: "IntoIterator", es: "HaciaIterador" },
    Par { en: "FromIterator", es: "DesdeIterador" },
    Par { en: "Display", es: "Muestra" },
    Par { en: "Debug", es: "Depura" },
    Par { en: "Clone", es: "Clona" },
    Par { en: "Copy", es: "Copia" },
    Par { en: "Drop", es: "Suelta" },
    Par { en: "ToString", es: "ATexto" },
    Par { en: "AsRef", es: "ComoRef" },
    Par { en: "AsMut", es: "ComoMut" },
    Par { en: "FromStr", es: "DesdeStr" },
    Par { en: "ToOwned", es: "APropio" },
    Par { en: "PartialEq", es: "EqParcial" },
    Par { en: "PartialOrd", es: "OrdParcial" },
    Par { en: "Sized", es: "ConTamano" },
    Par { en: "PhantomData", es: "DatoFantasma" },
    Par { en: "RefCell", es: "CeldaRef" },
    Par { en: "Cell", es: "Celda" },
    Par { en: "Path", es: "Ruta" },
    Par { en: "PathBuf", es: "RutaBuf" },
    Par { en: "File", es: "Archivo" },
    Par { en: "Duration", es: "Duracion" },
    Par { en: "Instant", es: "Instante" },
    Par { en: "OsString", es: "TextoOs" },
    Par { en: "CString", es: "TextoC" },
    Par { en: "Error", es: "Error" },
    // print family: bang stripped in translate
    Par { en: "print", es: "imprime" },
    Par { en: "eprintln", es: "imprimir_err" },
    Par { en: "eprint", es: "imprime_err" },
];

pub fn prelude_en_a_es(w: &str) -> Option<&'static str> {
    PRELUDE.iter().find(|p| p.en == w).map(|p| p.es)
}

pub fn prelude_es_a_en(w: &str) -> Option<&'static str> {
    PRELUDE.iter().find(|p| p.es == w).map(|p| p.en)
}

pub const SIN_BANG: &[(&str, &str)] = &[
    ("println", "imprimir"),
    ("print", "imprime"),
    ("eprintln", "imprimir_err"),
    ("eprint", "imprime_err"),
];
